---
- name: install pip3
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
- name: install borgmatic
  pip:
    name: borgmatic
    executable: pip3
- name: create /etc/borgmatic directory
  file:
    state: directory
    path: "/etc/borgmatic"
- name: init configuration
  template:
    src: config.yaml
    dest: /etc/borgmatic/config.yaml
    mode: "0600"
    owner: root
    group: root
- name: set environment variable for borg
  lineinfile:
    path: /root/.bashrc
    create: yes
    line: "{{ item }}"
  loop:
    - export BORG_REPO='ssh://{{ backup_server_user }}@{{ backup_server_host }}{{ repository_path }}'
    - export BORG_PASSPHRASE='{{ encryption_passphrase }}'
  no_log: True