---
- name: install pip3
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
- name: install borgmatic
  # borgmatic 1.4.8 extract/restore does not work properly
  # see https://projects.torsion.org/witten/borgmatic/issues/243#issuecomment-2109
  pip:
    name: borgmatic==1.3.26
    executable: pip3
- name: create /etc/borgmatic directory
  file:
    state: directory
    path: "/etc/borgmatic"
- name: init configuration
  template:
    src: config.yaml
    dest: /etc/borgmatic/config.yaml
    mode: "0600"
    owner: root
    group: root
- name: install cronjob to backup the local files
  template:
    src: cronjob.j2
    dest: /etc/cron.d/borgmatic
    mode: "0700"
    owner: root
    group: root