---
- name: get the borg binary
  get_url:
    url: "https://github.com/borgbackup/borg/releases/download/{{ borg_version }}/borg-linux64"
    dest: "/tmp/borg-linux64"
- name: get borg gpg signature
  get_url:
    url: "https://github.com/borgbackup/borg/releases/download/{{ borg_version }}/borg-linux64.asc"
    dest: "/tmp/borg-linux64.asc"
- name: import gpg public key necessary for the verification
  command: gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys "6D5B EF9A DD20 7580 5747 B70F 9F88 FB52 FAF7 B393"
- name: check validity of the file using gpg verify
  command: gpg --verify /tmp/borg-linux64.asc /tmp/borg-linux64
- name: move borg-linux64 to /usr/local/bin/borg
  copy:
    src: "/tmp/borg-linux64"
    dest: "/usr/local/bin/borg"
    remote_src: yes
- name: set execute permissions on /usr/local/bin/borg
  file:
    state: file
    path: /usr/local/bin/borg
    mode: "0755"
- name: set environment variable for borg
  lineinfile:
    path: /root/.bashrc
    create: yes
    line: "{{ item }}"
  loop:
    - export BORG_REPO='ssh://{{ backup_server_user }}@{{ backup_server_host }}{{ repository_path }}'
    - export BORG_PASSPHRASE='{{ repository_passphrase }}'
  no_log: yes