borgmatic_version: "1.3.26"
backup_server_user: "root"
backup_server_host: "borg.eccenca.local"
repository_path: "/data/borg"
source_directories:
  - /home
  - /etc
  - /var/log/syslog*
repository_passphrase: "supers3crets00394cret"
# Retention
keep_daily: 7
keep_weekly: 4
keep_monthly: 12
keep_yearly: 5
consistency_checks:
  - repository
  - archives
cron_min: "*"
cron_hour: "*"
cron_day_month: "*"
cron_month: "*"
cron_day_week: "*"